database:
    host: "127.0.0.1"
    port: "5432"
    name: "pharmacy_db"
    username: "ayesha"
    password: "password"
    options:
        sslmode:
            - disable
amqp:
    uri: "amqp://guest:guest@localhost:5672/"