version: '3.1'

services:

  database:
    image: postgres
    container_name: pharma
    ports:
      - 8081:8080
    environment:
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=ayesha
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database:/var/lib/postgresql