version: '3.1'

services:
  # api:
  #   depends_on:
  #     - database
  #   build: .
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - mynet
  database:
    image: postgres
    container_name: pharma
    ports:
      - 5432:5432
    networks:
      - mynet
    environment:
      POSTGRES_DB: pharmacy_db
      POSTGRES_USER: ayesha
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: 127.0.0.1
    volumes:
      - /home/pathao/Documents/storage/postgresql:/var/lib/postgresql/data

  consul:
    image: consul:latest
    ports:
      - 8500:8500
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    image: 'redis:alpine'
    ports:
        - '6379:6379'
networks:
  mynet:
    driver: bridge