version: '3.1'

services:
  web:
    build: .
    env_file:
      - .env
  database:
    image: postgres
    container_name: pharma
    ports:
      - 8081:8080
    environment:
      - POSTGRES_DB=pharmacy_db
      - POSTGRES_USER=ayesha
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=localhost
    volumes:
      - ./database:/var/lib/postgresql