#! /bin/sh
export NOTIFICATIONS_CONSUL_URL="127.0.0.1:8500" &&
export NOTIFICATIONS_CONSUL_PATH="pharmacy" &&
echo "ENV: NOTIFICATIONS_CONSUL_URL=" $NOTIFICATIONS_CONSUL_URL
echo "ENV: NOTIFICATIONS_CONSUL_PATH=" $NOTIFICATIONS_CONSUL_PATH

echo "putting consul config ..."
curl --request PUT --data-binary @config.yml http://localhost:8500/v1/kv/pharmacy

./PharmaProject serve
